import { CalendarDays, FileText, MapPin, PackageCheck } from "lucide-react";

export function BrandedReportHeader({
  branchName,
  companyName = "Domestic Express (pvt) ltd",
  accent,
  title,
  date,
  pageNumber = 1,
  pageCount = 1,
}) {
  const branch = toTitleCase(String(branchName || "Middeniya").trim() || "Middeniya");

  return (
    <div className="report-whatsapp-only report-whatsapp-header">
      <header className="report-brand-bar">
        <div className="report-wordmark-wrap">
          <strong className="report-wordmark">DOMEX</strong>
          <span>{companyName}</span>
        </div>
        <div className="report-brand-branch">
          <MapPin aria-hidden="true" />
          <div>
            <strong>{branch.toUpperCase()} BRANCH</strong>
            <span>Reliable Delivery. Every Time.</span>
          </div>
        </div>
      </header>

      <div className="report-heading-block">
        <p>Domex {branch} Branch</p>
        <h2>
          <span>{accent}</span> {title}
        </h2>
        <div className="report-heading-rule" />
      </div>

      <div className="report-meta-cards">
        <div className="report-meta-card report-meta-date">
          <CalendarDays aria-hidden="true" />
          <span><small>Date</small><strong>{date}</strong></span>
        </div>
        <div className="report-meta-card report-meta-page">
          <FileText aria-hidden="true" />
          <span><small>Page</small><strong>{pageNumber} / {pageCount}</strong></span>
        </div>
      </div>
    </div>
  );
}

export function BrandedReportFooter({ branchName, summaryLabel, summaryValue, showManager = true }) {
  const branch = toTitleCase(String(branchName || "Middeniya").trim() || "Middeniya");
  return (
    <footer className="report-whatsapp-only report-branded-footer">
      <div className="report-summary-panel">
        <span className="report-summary-icon"><PackageCheck aria-hidden="true" /></span>
        <span className="report-summary-copy">
          <small>{summaryLabel}</small>
          <strong>{summaryValue}</strong>
        </span>
        {showManager && (
          <span className="report-manager-signature">
            <i />
            <strong>Branch Manager</strong>
            <small>Domex {branch} Branch</small>
          </span>
        )}
        <span className="report-brand-seal">DOMEX<small>Courier Service</small></span>
      </div>
      <div className="report-footer-strip">
        <span><MapPin aria-hidden="true" /> {branch}, Sri Lanka</span>
        <span><CalendarDays aria-hidden="true" /> Generated by Daily Courier Report System</span>
      </div>
    </footer>
  );
}

function toTitleCase(value) {
  return value.toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());
}
